#!/bin/bash

set -eo pipefail

export GO15VENDOREXPERIMENT=1

go install github.com/bunniesandbeatings/go-flavor-parser/baduk

echo
echo "***** RUNNING"
echo

baduk github.com/bunniesandbeatings/go-flavor-parser/...
