#!/bin/bash

set -eo pipefail

export GO15VENDOREXPERIMENT=1

go build github.com/bunniesandbeatings/go-flavor-parser/...

echo
echo "***** RUNNING"
echo

baduk -output final/output.xml github.com/bunniesandbeatings/go-flavor-parser/...
